services:
  - type: web
    name: qr-ware-api
    env: python
    rootDir: ./backend
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn app:app --bind 0.0.0.0:${PORT}
    autoDeploy: true
